let mirrorElixir = 0;

let troops = [
{name: 'Knight', image: 'troops/knight.png', rarity: 'common', elixir: 3},
{name: 'Archers', image: 'troops/archers.png', rarity: 'common', elixir: 3},
{name: 'Giant', image: 'troops/giant.png', rarity: 'rare', elixir: 5},
{name: 'Archer Queen', image: 'troops/archer-queen.png', rarity: 'champion', elixir: 5},
{name: 'Barbarians', image: 'troops/barbarians.png', rarity: 'common', elixir: 5},
{name: 'Magic Archer', image: 'troops/magic-archer.png', rarity: 'legendary', elixir: 4},
{name: 'Gobins', image: 'troops/goblins.png', rarity: 'common', elixir: 2},
{name: 'Spear Gobins', image: 'troops/spear-goblin.png', rarity: 'common', elixir: 2},
{name: 'Goblin Hut', image: 'troops/goblin-hut.png', rarity: 'rare', elixir: 5},
{name: 'Bomber', image: 'troops/bomber.png', rarity: 'common', elixir: 2},
{name: 'Minion', image: 'troops/minion.png', rarity: 'common', elixir: 3},
{name: 'Zap', image: 'troops/zap.png', rarity: 'common', elixir: 2},
{name: 'Minion Horde', image: 'troops/minion-horde.png', rarity: 'common', elixir: 5},
{name: 'Goblin Gang', image: 'troops/goblin-gang.png', rarity: 'common', elixir: 3},
{name: 'Skeletons', image: 'troops/skeletons.png', rarity: 'common', elixir: 1},
{name: 'Skeleton Barrel', image: 'troops/skeleton-barrel.png', rarity: 'common', elixir: 3},
{name: 'Fire Spirit', image: 'troops/fire-spirit.png', rarity: 'common', elixir: 1},
{name: 'Electro Spirit', image: 'troops/electro-spirit.png', rarity: 'common', elixir: 1},
{name: 'Ice Spirit', image: 'troops/ice-spirit.png', rarity: 'common', elixir: 1},
{name: 'Arrow', image: 'troops/arrow.png', rarity: 'common', elixir: 3},
{name: 'Royal Giant', image: 'troops/royal-giant.png', rarity: 'common', elixir: 6},
{name: 'Bats', image: 'troops/bats.png', rarity: 'common', elixir: 2},
{name: 'Mortor', image: 'troops/mortor.png', rarity: 'common', elixir: 4},
{name: 'Skeleton Dragon', image: 'troops/skeleton-dragon.png', rarity: 'common', elixir: 4},
{name: 'Cannon', image: 'troops/cannon.png', rarity: 'common', elixir: 3},
{name: 'Elite Barbarian', image: 'troops/elite-barbarian.png', rarity: 'common', elixir: 4},
{name: 'Tesla', image: 'troops/tesla.png', rarity: 'common', elixir: 4},
{name: 'Royal Recruits', image: 'troops/royal-recruits.png', rarity: 'common', elixir: 7},
{name: 'Snowball', image: 'troops/snowball.png', rarity: 'common', elixir: 2},
{name: 'Rascals', image: 'troops/rascals.png', rarity: 'common', elixir: 5},
{name: 'Firecracker', image: 'troops/firecracker.png', rarity: 'common', elixir: 3},
{name: 'Royal Delivery', image: 'troops/royal-delivery.png', rarity: 'common', elixir: 3},
{name: 'Hog Rider', image: 'troops/hog-rider.png', rarity: 'rare', elixir: 4},
{name: 'Battle Ram', image: 'troops/battle-ram.png', rarity: 'rare', elixir: 4},
{name: 'Furnace', image: 'troops/furnace.png', rarity: 'rare', elixir: 4},
{name: 'Fireball', image: 'troops/fireball.png', rarity: 'rare', elixir: 4},
{name: 'Dart Goblin', image: 'troops/dart-goblin.png', rarity: 'rare', elixir: 3},
{name: 'Heal Spirit', image: 'troops/heal-spirit.png', rarity: 'rare', elixir: 1},
{name: 'Rocket', image: 'troops/rocket.png', rarity: 'rare', elixir: 6},
{name: 'Mega Minion', image: 'troops/mega-minion.png', rarity: 'rare', elixir: 3},
{name: 'Inferno Tower', image: 'troops/inferno-tower.png', rarity: 'rare', elixir: 5},
{name: 'Musketeer', image: 'troops/musketeer.png', rarity: 'rare', elixir: 4},
{name: 'Three Musketeers', image: 'troops/three-musketeers.png', rarity: 'rare', elixir: 9},
{name: 'Ice Golem', image: 'troops/ice-golem.png', rarity: 'rare', elixir: 2},
{name: 'Valkyrie', image: 'troops/valkyrie.png', rarity: 'rare', elixir: 4},
{name: 'Tombstone', image: 'troops/tombstone.png', rarity: 'rare', elixir: 3},
{name: 'Elixir Collector', image: 'troops/elixir-collector.png', rarity: 'rare', elixir: 6},
{name: 'Barbarian Hut', image: 'troops/barbarian-hut.png', rarity: 'rare', elixir: 6},
{name: 'Wizard', image: 'troops/wizard.png', rarity: 'rare', elixir: 5},
{name: 'Bomb Tower', image: 'troops/bomb-tower.png', rarity: 'rare', elixir: 4},
{name: 'Flying Machine', image: 'troops/flying-machine.png', rarity: 'rare', elixir: 4},
{name: 'Royal Hog', image: 'troops/royal-hog.png', rarity: 'rare', elixir: 5},
{name: 'Zappies', image: 'troops/zappies.png', rarity: 'rare', elixir: 5},
{name: 'Elixir Golem', image: 'troops/elixir-golem.png', rarity: 'rare', elixir: 3},
{name: 'Battle Healer', image: 'troops/battle-healer.png', rarity: 'rare', elixir: 4},
{name: 'Earthquake', image: 'troops/earthquake.png', rarity: 'rare', elixir: 3},
{name: 'Mini Pekka', image: 'troops/mini-pekka.png', rarity: 'rare', elixir: 4},
{name: 'Prince', image: 'troops/prince.png', rarity: 'epic', elixir: 5},
{name: 'Electro Dragon', image: 'troops/electro-dragon.png', rarity: 'epic', elixir: 5},
{name: 'Balloon', image: 'troops/balloon.png', rarity: 'epic', elixir: 5},
{name: 'Tornado', image: 'troops/tornado.png', rarity: 'epic', elixir: 3},
{name: 'Freeze', image: 'troops/freeze.png', rarity: 'epic', elixir: 4},
{name: 'Bowler', image: 'troops/bowler.png', rarity: 'epic', elixir: 5},
{name: 'Barbarian Barrel', image: 'troops/barbarian-barrel.png', rarity: 'epic', elixir: 2},
{name: 'Wallbreaker', image: 'troops/wallbreaker.png', rarity: 'epic', elixir: 2},
{name: 'Dark Prince', image: 'troops/dark-prince.png', rarity: 'epic', elixir: 4},
{name: 'Rage', image: 'troops/rage.png', rarity: 'epic', elixir: 2},
{name: 'Mirror', image: 'troops/mirror.png', rarity: 'epic', elixir: mirrorElixir},
{name: 'Electro Giant', image: 'troops/electro-giant.png', rarity: 'epic', elixir: 7},
{name: 'Goblin Giant', image: 'troops/goblin-giant.png', rarity: 'epic', elixir: 6},
{name: 'Poison', image: 'troops/poison.png', rarity: 'epic', elixir: 4},
{name: 'Baby Dragon', image: 'troops/baby-dragon.png', rarity: 'epic', elixir: 4},
{name: 'Goblin Barrel', image: 'troops/goblin-barrel.png', rarity: 'epic', elixir: 3},
{name: 'Witch', image: 'troops/witch.png', rarity: 'epic', elixir: 5},
{name: 'Skeleton Army', image: 'troops/skeleton-army.png', rarity: 'epic', elixir: 3},
{name: 'Pekka', image: 'troops/pekka.png', rarity: 'epic', elixir: 7},
{name: 'Guards', image: 'troops/guards.png', rarity: 'epic', elixir: 3},
{name: 'Lightning', image: 'troops/lightning.png', rarity: 'epic', elixir: 6},
{name: 'Clone', image: 'troops/clone.png', rarity: 'epic', elixir: 3},
{name: 'Goblin Drill', image: 'troops/goblin-drill.png', rarity: 'epic', elixir: 4},
{name: 'Giant Skeleton', image: 'troops/giant-skeleton.png', rarity: 'epic', elixir: 6},
{name: 'Cannon Cart', image: 'troops/cannon-cart.png', rarity: 'epic', elixir: 5},
{name: 'Executioner', image: 'troops/executioner.png', rarity: 'epic', elixir: 5},
{name: 'X-bow', image: 'troops/x-bow.png', rarity: 'epic', elixir: 6},
{name: 'Golem', image: 'troops/golem.png', rarity: 'epic', elixir: 8},
{name: 'Hunter', image: 'troops/hunter.png', rarity: 'epic', elixir: 4},
{name: 'Princess', image: 'troops/princess.png', rarity: 'legendary', elixir: 3},
{name: 'Lumberjack', image: 'troops/lumberjack.png', rarity: 'legendary', elixir: 4},
{name: 'Inferno Dragon', image: 'troops/inferno-dragon.png', rarity: 'legendary', elixir: 4},
{name: 'Ram Rider', image: 'troops/ram-rider.png', rarity: 'legendary', elixir: 5},
{name: 'The Log', image: 'troops/the-log.png', rarity: 'legendary', elixir: 2},
{name: 'Lava Hound', image: 'troops/lava-hound.png', rarity: 'legendary', elixir: 7},
{name: 'Miner', image: 'troops/miner.png', rarity: 'legendary', elixir: 3},
{name: 'Electro Wizard', image: 'troops/electro-wizard.png', rarity: 'legendary', elixir: 4},
{name: 'Ice Wizard', image: 'troops/ice-wizard.png', rarity: 'legendary', elixir: 3},
{name: 'Mega Knight', image: 'troops/mega-knight.png', rarity: 'legendary', elixir: 7},
{name: 'Phoenix', image: 'troops/phoenix.png', rarity: 'legendary', elixir: 4},
{name: 'Night Witch', image: 'troops/night-witch.png', rarity: 'legendary', elixir: 4},
{name: 'Mother Witch', image: 'troops/mother-witch.png', rarity: 'legendary', elixir: 4},
{name: 'Royal Ghost', image: 'troops/royal-ghost.png', rarity: 'legendary', elixir: 3},
{name: 'Graveyard', image: 'troops/graveyard.png', rarity: 'legendary', elixir: 5},
{name: 'Sparky', image: 'troops/sparky.png', rarity: 'legendary', elixir: 6},
{name: 'Bandit', image: 'troops/bandit.png', rarity: 'legendary', elixir: 3},
{name: 'Fisherman', image: 'troops/fisherman.png', rarity: 'legendary', elixir: 3},
{name: 'Skeleton King', image: 'troops/skeleton-king.png', rarity: 'champion', elixir: 4},
{name: 'Monk', image: 'troops/monk.png', rarity: 'champion', elixir: 5},
{name: 'Golden Knight', image: 'troops/golden-knight.png', rarity: 'champion', elixir: 4},
{name: 'Mighty Miner', image: 'troops/mighty-miner.png', rarity: 'champion', elixir: 4},
];


/* Code for generating array for convenience
let troopTemp = '';
troopArray.forEach((troop) => {
    let imageName = troop.replace(' ', '-');
    imageName = imageName.toLowerCase();
    troopTemp += `{name: '${troop}', image: 'troops/${imageName}.png', rarity: '', elixir: ''},<br>`
});
document.querySelector('.generate-troops').innerHTML = troopTemp;*/